name: MSBuild

on: [push]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        mode: ["Debug", "Release"]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{matrix.mode}} ${{env.SOLUTION_FILE_PATH}}
      
    - name: Archive files
      uses: actions/upload-artifact@v2
      with:
        name: arcdps_mock_${{ matrix.mode }}
        path: |
          x64/${{ matrix.mode }}/*.exe
          x64/${{ matrix.mode }}/*.dll
          x64/${{ matrix.mode }}/*.pdb
