name: CMake with vcpkg

on: [ push ]

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest ]
        presets: [ release-windows ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # install cmake and ninja
      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@main
        id: runvcpkg
        with:
          # This specifies the location of vcpkg, where it is going to be restored from cache, or create from scratch.
          # vcpkgDirectory: '${{ github.workspace }}/vcpkg'

          # The Git commit id of vcpkg to be checked out. This is only needed because we are not using a submodule.
          vcpkgGitCommitId: 'f5800a22acb14d7f753e8be12fe5ec2bc999ab44'

          # The vcpkg.json file, which will be part of cache key computation.
          #          vcpkgJsonGlob: '${{ github.workspace }}/vcpkg.json'

          # don't run vcpkg install in the project, let run-cmake do it.
          runVcpkgInstall: false

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.presets }}
          buildPreset: ${{ matrix.presets }}

      - name: Archive files
        uses: actions/upload-artifact@v4
        with:
          name: arcdps_mock_${{ matrix.presets }}
          path: |
            cmake-build/${{ matrix.presets }}/arcdps_collector/*.dll
            cmake-build/${{ matrix.presets }}/arcdps_collector/*.pdb
            cmake-build/${{ matrix.presets }}/arcdps_mock/*.exe
            cmake-build/${{ matrix.presets }}/arcdps_mock/*.pdb
